language: csharp
script:
    - xbuild /p:Configuration=Release AirstrikesV.sln
notifications:
  webhooks:
    urls:
      - https://skyhook.glitch.me/api/webhooks/439478521732136970/hhXwKKKH0bw4o204agwXbYaxm2E19u8_4VxjTJxL_hnncUKPkAIb-yKFLUx1rPcLeoWn/travis
install:
    - sudo apt-get install nuget
    - sudo nuget install CitizenFX.Core

branches:
    only:
        - master

deploy:
    provider: releases
    api_key: $GITHUB_API_KEY
    file: "/home/travis/build/TomGrobbe/release/vMenu/builds/AirstrikesV.zip"
    skip_cleanup: true
    prerelease: false
    draft: true
    name: "[Release] AirstrikesV"
    on:
        branch: 
        - master
